Fix a type error upon reconnect
Resolves the following error, that occurs if the connection is lost
(e.g. server shutdown):

    server closed the connection unexpectedly
            This probably means the server terminated abnormally
            before or while processing the request.

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File ".../src/pg_activity/.venv/bin/pg_activity", line 8, in <module>
        sys.exit(main())
      File ".../src/pg_activity/pgactivity/cli.py", line 416, in main
        newdataobj = dataobj.try_reconnect()
      File ".../src/pg_activity/pgactivity/data.py", line 122, in try_reconnect
        pg_conn = pg.connect(**self.dsn_parameters)
    TypeError: connect() missing 1 required positional argument: 'dsn'

The 'dsn' argument of pg.connect() was incorrectly required.