Fix some tests for versions <= 9.6
Some tests wouldn't work pre pg 10 because of "unknown type" warnings &
errors.

[local]:5439 postgres@postgres=# CREATE TABLE x AS (SELECT 'init' s);
WARNING:  column "s" has type "unknown"
DETAIL:  Proceeding with relation creation anyway.
SELECT 1
[local]:5439 postgres@postgres=# CREATE INDEX CONCURRENTLY ON x(s);
ERROR:  data type unknown has no default operator class for access method "btree"
HINT:  You must specify an operator class for the index or define a default operator class for the data type.
[local]:5439 postgres@postgres=# \d x
       Table "public.x"
 Column |  Type   | Modifiers
--------+---------+-----------
 s      | unknown |

Fixed with a cast :

[local]:5439 postgres@postgres=# CREATE TABLE y AS (SELECT 'init'::text s);
SELECT 1