Ignore a mypy error about getattr() usage in sorted()
The following error pops up with mypy version 0.790:

    pgactivity/activities.py:152: error: Returning Any from function declared to return "_SupportsLessThan"

We cannot simply resolve this, so we ignore it and add a TODO about a
possible refactoring to avoid the getattr().