Do not use term.formatter()
This does not work with blessed from Debian/buster:

  Traceback (most recent call last):
    File "/usr/lib/python3/dist-packages/blessed/formatters.py", line 82, in __call__
      attr = curses.tparm(self.encode('latin1'), *args).decode('latin1')
  TypeError: an integer is required (got type str)

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "/usr/bin/pg_activity", line 260, in <module>
      ui.main(options)
    File "/usr/lib/python3/dist-packages/pgactivity/ui.py", line 113, in main
      width=width,
    File "/usr/lib/python3/dist-packages/pgactivity/widgets.py", line 15, in boxed
      border_formatter = term.formatter(border_color)
    File "/usr/lib/python3/dist-packages/blessed/formatters.py", line 92, in __call__
      self._name, args, err))
  TypeError: A native or nonexistent capability template, 'formatter' received invalid argument ('yellow',): an integer is required (got type str). You probably misspelled a formatting call like `bright_red'